[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
default = []
idl-build = ["anchor-spl/idl-build", "anchor-lang/idl-build"] 
cpi = ["no-entrypoint"]
no-entrypoint = []

[programs.localnet]
# provenance_project  = "CeHSRR3qLQjzBgmAeat75wuoeynUagCCwR1nbUNTG76T"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "devnet"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
