version: '3.8'

services:
  solana_dev:
    container_name: solana_dev_env
    build:
      context: .
      dockerfile: solana-dev.Dockerfile
    
    # 현재 프로젝트 폴더 전체를 컨테이너 내부의 /app 폴더와 연결합니다.
    # 이렇게 하면 PC에서 코드를 수정하면 컨테이너 안에도 바로 반영됩니다.
    volumes:
      - .:/app
      # ✅ PC의 지갑을 담을 볼륨을 컨테이너의 '폴더'와 연결합니다.
      - solana_config:/root/.config/solana
      # solana_ledger 볼륨을 컨테이너의 test-ledger 폴더에 연결합니다.
      - solana_ledger:/app/test-ledger
    
    # 개발 작업을 위해 컨테이너를 계속 실행 상태로 유지합니다.
    command: sleep infinity
    ports:
    - "8899:8899" # RPC 포트
    - "8900:8900" # Faucet 포트
    environment:
      ANCHOR_PROVIDER_URL: http://localhost:8899
      ANCHOR_WALLET: /root/.config/solana/id.json

# 파일 최하단에 아래 내용을 추가하여 Docker 볼륨을 정의합니다.
volumes:
  solana_config:
  solana_ledger: