version: '3.8'

services:
  solana_dev: # 솔라나 개발 환경 
    container_name: solana_dev_env
    build:
      context: .
      dockerfile: solana-dev.Dockerfile
    
    # 현재 프로젝트 폴더 전체를 컨테이너 내부의 /app 폴더와 연결합니다.
    # 이렇게 하면 PC에서 코드를 수정하면 컨테이너 안에도 바로 반영됩니다.
    volumes:
      - .:/app
      # ✅ PC의 지갑을 담을 볼륨을 컨테이너의 '폴더'와 연결합니다.
      - solana_config:/root/.config/solana
      # solana_ledger 볼륨을 컨테이너의 test-ledger 폴더에 연결합니다.
      - solana_ledger:/app/test-ledger
    
    # 개발 작업을 위해 컨테이너를 계속 실행 상태로 유지합니다.
    command: >
      sh -c "
        solana-test-validator \
          --ledger /app/test-ledger \
          --rpc-port 8899 \
          --faucet-port 8900 \
          --bind-address 0.0.0.0
      "
    ports:
    - "8899:8899" # RPC 포트
    - "8900:8900" # Faucet 포트
    environment:
      ANCHOR_PROVIDER_URL: http://localhost:8899
      ANCHOR_WALLET: /root/.config/solana/id.json
  db: # MySQL 데이터베이스 서비스
    image: mysql:8.0
    container_name: pomodoro-db-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pomodoro_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306" # PC에서 DB 접속 시 사용
    restart: unless-stopped
volumes:
  solana_config:
  solana_ledger:
  mysql_data: # [신규] MySQL 데이터 저장을 위한 볼륨